import Category from '../models/domain/category'
import Receipt from '../models/domain/receipt'
import { ReceiptCategory } from '../models/enums'


const MerchantCategoryMapping = {
    'ActBlue Civics Inc': ReceiptCategory.DONATIONS,
    'Advance Auto Parts': ReceiptCategory.AUTO_REPAIR,
    'Airbnb': ReceiptCategory.TRAVEL,
    'Airbnb Payments Inc': ReceiptCategory.TRAVEL,
    'Andy\'s Frozen Custard': ReceiptCategory.FAST_FOOD,
    'Atomic Bean Cafe': ReceiptCategory.COFFEE,
    'Back of the Yards Coffeehouse': ReceiptCategory.COFFEE,
    'Amazon.com': ReceiptCategory.SHOPPING,
    'Amazon Student': ReceiptCategory.SHOPPING,
    'Apple': ReceiptCategory.SHOPPING,
    'Arby\'s': ReceiptCategory.FAST_FOOD,
    'Best Buy': ReceiptCategory.SHOPPING,
    'Buddy': ReceiptCategory.COFFEE,
    'Black & Brew Lake Morton': ReceiptCategory.COFFEE,
    'Black & Brew Southside': ReceiptCategory.COFFEE,
    'CafePress': ReceiptCategory.SHOPPING,
    'Chi Kin': ReceiptCategory.FAST_FOOD,
    'China Moon': ReceiptCategory.FAST_FOOD,
    'Cloud Imperium Games Corporation': ReceiptCategory.GAMING,
    'Collective Espresso Northside': ReceiptCategory.GAMING,
    'Ciao Bella Pizza and Pasta has been scheduled': ReceiptCategory.FAST_FOOD,
    'COOLER INTERNATIONAL CO': ReceiptCategory.PROJECTS,
    'Cumin': ReceiptCategory.FAST_FOOD,
    'Curious Joe': ReceiptCategory.PROJECTS,
    'Deeper Roots Coffee': ReceiptCategory.COFFEE,
    'Dollop Coffee C': ReceiptCategory.COFFEE,
    'Dunkin Donuts': ReceiptCategory.COFFEE,
    'Pavement Fenway': ReceiptCategory.COFFEE,
    'Digital Ocean': ReceiptCategory.HOSTING,
    'DigitalOcean': ReceiptCategory.HOSTING,
    'DoorDash': ReceiptCategory.FAST_FOOD,
    'Drive Up': ReceiptCategory.FAST_FOOD,
    'Electronic Arts': ReceiptCategory.SHOPPING,
    'ECHO Coffee House': ReceiptCategory.COFFEE,
    'Empanadas Aqui Food Truck': ReceiptCategory.FAST_FOOD,
    'Fastmail Pty Ltd': ReceiptCategory.HOSTING,
    'Famous Footwear': ReceiptCategory.SHOPPING,
    'Five Below': ReceiptCategory.SHOPPING,
    'Fountain Pen Revolution': ReceiptCategory.SHOPPING,
    'Google Play': ReceiptCategory.SHOPPING,
    'GrubHub Seamless': ReceiptCategory.FAST_FOOD,
    'Goggles': ReceiptCategory.HEALTH,
    'Greenmount Coffee Lab': ReceiptCategory.SHOPPING,
    'Groupon Inc': ReceiptCategory.SHOPPING,
    'High Grounds Coffee Roasters': ReceiptCategory.COFFEE,
    'Humble Bundle': ReceiptCategory.GAMING,
    'Instacart': ReceiptCategory.GROCERIES,
    'Internet Archive': ReceiptCategory.DONATIONS,
    'iTunes and App Store': ReceiptCategory.SHOPPING,
    'Lola': ReceiptCategory.COFFEE,
    'LOWE\'S HOME CENTERS': ReceiptCategory.PROJECTS,
    'Lyft': ReceiptCategory.TRANSPORTATION,
    'LIMITLESS Coffee & Tea': ReceiptCategory.COFFEE,
    'MAK Restaurant': ReceiptCategory.RESTAURANT,
    'Micro Center': ReceiptCategory.SHOPPING,
    'mTicket': ReceiptCategory.TRANSPORTATION,
    'Netflix': ReceiptCategory.ENTERTAINMENT,
    'northern tool and equipment': ReceiptCategory.PROJECTS,
    'Northside Asian Kitchen': ReceiptCategory.FAST_FOOD,
    'Oath Craft Pizza': ReceiptCategory.FAST_FOOD,
    'PARAMOUNT': ReceiptCategory.ENTERTAINMENT,
    'Parking': ReceiptCategory.TRANSPORTATION,
    'Panther Coffee': ReceiptCategory.COFFEE,
    'Parkmobile USA Inc': ReceiptCategory.PARKING,
    'PayPal Giving Fund': ReceiptCategory.DONATIONS,
    'Patreon': ReceiptCategory.DONATIONS,
    'Patriot Coffee': ReceiptCategory.COFFEE,
    'PetSmart': ReceiptCategory.PET,
    'Pressed LKLD': ReceiptCategory.COFFEE,
    'Progressive Direct Insurance': ReceiptCategory.AUTO_INSURANCE,
    'Relay FM': ReceiptCategory.DONATIONS,
    'Riot Games Inc': ReceiptCategory.GAMING,
    'RockAuto': ReceiptCategory.PET,
    'Ritual': ReceiptCategory.FAST_FOOD,
    'rositas': ReceiptCategory.FAST_FOOD,
    'Secretlab': ReceiptCategory.SHOPPING,
    'SunPass': ReceiptCategory.TRANSPORTATION,
    'Sweet Brew': ReceiptCategory.COFFEE,
    'Society': ReceiptCategory.SHOPPING,
    'Solomid Corporation': ReceiptCategory.SHOPPING,
    'Spotify USA Inc': ReceiptCategory.ENTERTAINMENT,
    'Starbucks': ReceiptCategory.ENTERTAINMENT,
    'Sunoco': ReceiptCategory.TRANSPORTATION,
    'SWEET CUP CAFE': ReceiptCategory.COFFEE,
    'Target': ReceiptCategory.GROCERIES,
    'Teespring': ReceiptCategory.SHOPPING,
    'Telemetry Coffee Roasters': ReceiptCategory.COFFEE,
    'Texas Roadhouse': ReceiptCategory.RESTAURANT,
    'The Economist Newspaper NA Inc': ReceiptCategory.NEWS,
    'The New York Times Co': ReceiptCategory.NEWS,
    'The Home Depot': ReceiptCategory.PROJECTS,
    'The Kidd Coffee Company': ReceiptCategory.COFFEE,
    'Thread Coffee Roasters': ReceiptCategory.COFFEE,
    'Tire Rack': ReceiptCategory.AUTO_MAINTENANCE,
    'TRACTORSUPPLY': ReceiptCategory.PROJECTS,
    'TractorSupply': ReceiptCategory.PROJECTS,
    'Tractor Supply Company': ReceiptCategory.PROJECTS,
    'Tucows Corp': ReceiptCategory.HOSTING,
    'Twitch Interactive': ReceiptCategory.ENTERTAINMENT,
    'Uber': ReceiptCategory.TRANSPORTATION,
    'Udemy': ReceiptCategory.EDUCATION,
    'Unfiltered Lakeland': ReceiptCategory.COFFEE,
    'Unidos Por Puerto Rico': ReceiptCategory.DONATIONS,
    'Urbana Cafe': ReceiptCategory.FAST_FOOD,
    'Valve Corp': ReceiptCategory.GAMING,
    'Vistaprint Netherlands B': ReceiptCategory.SHOPPING,
    'Walmart': ReceiptCategory.SHOPPING,
    'Wendy\'s': ReceiptCategory.FAST_FOOD,
    'Wikimedia Foundation': ReceiptCategory.DONATIONS,
    'Wing Box': ReceiptCategory.FAST_FOOD,
    'Zapier': ReceiptCategory.PROJECTS,
}


interface MerchantCategoryHelperContext {}

class MerchantCategoryHelper {

    constructor(
        private ctx: MerchantCategoryHelperContext
    ) {}

    categorize(normalizedMerchantName: string): ReceiptCategory {
        const category = MerchantCategoryMapping[normalizedMerchantName]
        return category || ReceiptCategory.UNCATEGORIZED
    }

}

export default MerchantCategoryHelper
